# config.toml

# Configurações do tema do Streamlit para combinar com a identidade da FJG
[theme]

# Cor primária usada em elementos interativos
primaryColor = "#004A7F"

# Cor de fundo principal da aplicação
backgroundColor = "#F0F2F6"

# Cor de fundo para elementos como a sidebar e o HEADER SUPERIOR
secondaryBackgroundColor = "#FFFFFF"

# Cor principal do texto
textColor = "#31333F"

# Fonte a ser usada
font = "sans serif"